"""
Message Models - Pydantic schemas for individual chat messages.

=== What are Pydantic models? ===
Pydantic models are Python classes that define the exact shape of data flowing
through the API. They handle validation (rejecting bad data) and serialization
(converting Python objects to JSON and back) automatically.

=== What this file defines ===
This file contains schemas for individual messages within conversations:
  - MessageCreate:   Data sent when a customer sends a new message
  - MessageResponse: Full message data returned by the API
  - ChatFeedback:    Thumbs up/down rating on an AI response
  - ChatRequest:     Simplified chat input used by the widget API
  - ChatResponse:    The AI's response along with metadata

=== Message flow overview ===
1. Customer types a message in the chat widget
2. Frontend sends a ChatRequest to the backend
3. Backend creates the customer's message (role="customer")
4. Backend searches the knowledge base for relevant context
5. Backend generates an AI response using the context
6. Backend creates the AI's message (role="ai") with confidence and sources
7. Backend returns a ChatResponse containing the AI message + metadata

=== Relationship to the database ===
The "messages" table stores one row per message. Each message belongs to exactly
one conversation (via conversation_id). Messages are the lowest-level entity in
the data hierarchy: Organization -> Bot -> Conversation -> Message.
"""

from pydantic import BaseModel
from datetime import datetime


class MessageCreate(BaseModel):
    """
    Schema for creating a new message (typically from a customer).

    Used by: POST /messages endpoint (internal use by the chat pipeline)
    Purpose: Records a new message in the database

    This is the raw message creation model used internally. External clients
    (like the chat widget) typically use the higher-level ChatRequest model
    instead, which handles conversation creation and AI response generation.
    """

    # The conversation this message belongs to. Can be None for the very first
    # message in a new conversation -- in that case, the backend creates a new
    # conversation and fills this in automatically.
    conversation_id: str | None = None

    # The bot this message is directed to. Required so the backend knows which
    # AI configuration and knowledge base to use for generating a response.
    bot_id: str

    # The actual text content of the message (what the customer typed).
    content: str

    # Which messaging platform this message came from. Helps the backend
    # format responses appropriately (e.g., WhatsApp supports different
    # formatting than the web widget).
    channel: str = "website"

    # The unique identifier of the customer who sent this message.
    # Used to associate messages with a customer profile and track
    # conversation history across sessions.
    customer_id: str | None = None

    # Optional file attachments sent with the message (images, documents, etc.).
    # Each attachment is a dict with keys like "url", "type", "filename".
    # None means no attachments; an empty list also means no attachments.
    attachments: list[dict] | None = None


class MessageResponse(BaseModel):
    """
    Schema for message data returned by the API.

    Used by: All endpoints that return messages (chat responses, conversation history)
    Sent to: The chat widget and agent dashboard to render message bubbles

    Contains the message content plus AI-specific metadata that helps with
    debugging, transparency, and quality monitoring.
    """

    # Unique identifier for this message (UUID string from the database).
    id: str

    # The conversation this message belongs to. Used to group messages together
    # and maintain chronological order within a conversation.
    conversation_id: str

    # Who sent this message. Determines how the frontend styles the message bubble:
    #   - "customer": Sent by the end user (right-aligned, colored bubble)
    #   - "ai":       Generated by the AI bot (left-aligned, with bot avatar)
    #   - "agent":    Sent by a human support agent (left-aligned, with agent avatar)
    role: str  # customer | ai | agent

    # The text content of the message.
    content: str

    # File attachments included with this message. Each dict typically contains:
    #   - "url": Where the file is stored
    #   - "type": MIME type (e.g., "image/png")
    #   - "filename": Original file name
    # Empty list if no attachments.
    attachments: list[dict] = []

    # References to the knowledge base chunks that were used to generate this
    # AI response. Each dict typically contains:
    #   - "chunk_id": The ID of the source chunk
    #   - "doc_id": The document it came from
    #   - "content": A snippet of the matched text
    #   - "score": How relevant the chunk was (similarity score)
    # Empty for customer and agent messages. Populated for AI messages.
    # Enables the "Sources" feature in the chat widget.
    source_chunks: list[dict] = []

    # How confident the AI is in its response, from 0.0 (no confidence) to
    # 1.0 (fully confident). Based on the similarity scores of matched chunks.
    # None for non-AI messages. Low confidence may trigger the fallback message
    # or escalation to a human agent.
    confidence_score: float | None = None

    # The detected intent/topic of the customer's message (e.g., "billing",
    # "product-question", "complaint", "greeting"). Classified by the AI.
    # None for non-AI messages. Used in analytics to track what customers
    # ask about most frequently.
    intent: str | None = None

    # When this message was created/sent. Used to display timestamps in the
    # chat UI and for ordering messages chronologically.
    created_at: datetime | None = None


class ChatFeedback(BaseModel):
    """
    Schema for customer feedback on an AI response.

    Used by: POST /messages/{message_id}/feedback endpoint
    Sent by: The thumbs-up/thumbs-down buttons shown below AI responses

    Feedback is essential for improving the AI over time. Low-rated responses
    can be reviewed by the bot owner to improve knowledge base content or
    adjust custom rules.
    """

    # The ID of the AI message being rated. Links to a specific message in
    # the "messages" table. Only AI messages can receive feedback.
    message_id: str

    # The rating the customer gave:
    #   - "thumbs_up":   The response was helpful and accurate
    #   - "thumbs_down": The response was unhelpful, wrong, or confusing
    rating: str  # thumbs_up | thumbs_down

    # Optional free-text comment explaining the rating. Especially valuable
    # for thumbs-down ratings -- knowing WHY a response was bad helps the
    # bot owner fix the issue (e.g., "The pricing info is outdated").
    comment: str | None = None


class ChatRequest(BaseModel):
    """
    Schema for the main chat endpoint used by the widget and external integrations.

    Used by: POST /chat endpoint
    Sent by: The chat widget's message input form

    This is the primary way external clients interact with the bot. It's a
    higher-level abstraction than MessageCreate -- the backend handles all the
    complexity of creating conversations, searching knowledge, and generating
    AI responses behind this simple interface.
    """

    # The bot to send this message to. Required so the backend loads the
    # correct AI configuration and knowledge base.
    bot_id: str

    # The customer's message text.
    message: str

    # The existing conversation ID to continue. If None, the backend creates
    # a new conversation. If provided, the message is appended to the existing
    # conversation, preserving chat history for context-aware AI responses.
    conversation_id: str | None = None

    # The messaging channel this request came from. Defaults to "website" for
    # the embedded chat widget. Other integrations set this to their channel.
    channel: str = "website"

    # Optional customer identifier. Helps the backend link messages to a
    # returning customer and load their conversation history.
    customer_id: str | None = None

    # Optional customer name. Used for personalization in AI responses
    # (e.g., "Hi Jane, ...") and shown in the agent dashboard.
    customer_name: str | None = None


class ChatResponse(BaseModel):
    """
    Schema for the AI's response to a chat message.

    Used by: POST /chat endpoint (returned as the response body)
    Sent to: The chat widget, which renders the AI's reply

    This bundles the AI's response with useful metadata. The chat widget uses
    the message content for display, the sources for a "Learn more" feature,
    and the handoff flag to show an escalation notice.
    """

    # The full AI-generated message, including all metadata (content, sources,
    # confidence, intent). This is what gets rendered as a chat bubble.
    message: MessageResponse

    # The conversation ID this message belongs to. If this was the first message
    # (no conversation_id in the request), this is the ID of the newly created
    # conversation. The frontend stores this and sends it with subsequent
    # messages to continue the same conversation thread.
    conversation_id: str

    # The knowledge base sources that informed the AI's response. Each dict
    # typically contains the document name and a relevant text snippet.
    # Displayed as expandable "Sources" below the AI's message so customers
    # can verify the information or read more.
    sources: list[dict] = []

    # The AI's overall confidence in its response, from 0.0 to 1.0.
    # The widget might show a subtle indicator if confidence is low, or
    # the backend may auto-escalate when confidence drops below a threshold.
    confidence: float = 0.0

    # The detected intent of the customer's message. The widget can use this
    # for analytics tracking or to trigger specific UI behaviors
    # (e.g., showing a special card for "pricing" intents).
    intent: str = "unknown"

    # Whether the conversation has been escalated to a human agent.
    # True means the AI determined it couldn't help and triggered a handoff.
    # The widget should show a message like "Connecting you to a human agent..."
    # and potentially display a wait time estimate.
    handoff: bool = False
